name: Organize Files on PR

on:
  pull_request:
    types:
      - opened
jobs:
  move_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract label
        id: extract-label
        run: |
          pr_number=${{ github.event.pull_request.number }}
          label=$(curl -s "https://api.github.com/repos/${{ github.repository }}/issues/$pr_number/labels" | jq -r '.[0].name')
          echo "::set-output name=label::$label"

      - name: Update RST File
        run: | 
          label=${{ steps.extract-label.outputs.label }}
          python script.py "$label"
          sed -i "s/Label Value: .*/Label Value: $label/" /home/runner/work/Traceability/Traceability/*.rst

      - name: Check for label and move files
        id: move-files
        run: |
          if [ -n "$LABEL" ]; then
            mkdir -p "$LABEL"
            mv *.rst "$LABEL/"
          fi
        env:
          LABEL: ${{ github.event.pull_request.labels[0].name }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: after organize the files
          branch: featureworkitem1
