name: Organize Files on PR

on:
  pull_request:
    types:
      - opened
jobs:
  move_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Labels
        run: sed -i "s/{labels}/$GITHUB_EVENT_LABELS/g" /home/runner/work/Traceability/Traceability/sw_req.rst

      - name: Check for label and move files
        id: move-files
        run: |
          if [ -n "$LABEL" ]; then
            mkdir -p "$LABEL"
            mv *.rst "$LABEL/"
          fi
        env:
          LABEL: ${{ github.event.pull_request.labels[0].name }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: after organize the files
          branch: featureworkitem1
   
