name: Organize Files on PR

on:
  pull_request:
    types:
      - opened
      - labeled

jobs:
  move_files:
    runs-on: ubuntu-latest

    steps:
      - name: Check for label and move files
        id: move-files
        run: |
          if [ -n "$LABEL" ]; then
            mkdir -p "$LABEL"
            mv *.txt "$LABEL/"
          fi
        env:
          LABEL: ${{ github.event.pull_request.labels[0].name }}
